run:
  skip-dirs:
    - .github

linters-settings:
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  misspell:
    locale: US
  govet:
    disable:
      - shadow
      - nilness
    enable-all: true

linters:
  enable:
    - gofmt
    - golint
    - gocyclo
    - misspell
    - bodyclose
    - govet
  disable:
    - errcheck
  disable-all: false
  fast: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
